### ISSUE TITLE
Step 4 SimeonChoi

### ISSUE THREAD

**Issue by SkuzyBae** [anamartinovici/githubfun#111] opened 2022-04-14 15:42 UTC
Test step 4

**Comment by anamartinovici** [comment] 2022-04-14 17:08
Hi, @SkuzyBae 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by SkuzyBae** [comment] 2022-04-14 20:21
Hi,

I’ve been trying to create a clone of the repository but I keep getting this error message:

***@***.***

I have already accepted your invite and restarted multiple times.

Sincerely,
Simeon

**Comment by anamartinovici** [comment] 2022-04-15 10:44
Hi, @SkuzyBae 

The error is not visible in your message: 
![image](https://user-images.githubusercontent.com/20222657/163561946-73606884-9572-4777-9a2b-5fc47944e605.png)

I notice you've managed to commit & push to this repository, so I assume the problem is fixed. If you have remaining issues or questions, let me know. Otherwise, please close this issue.

**Comment by anamartinovici** [comment] 2022-04-20 12:36
Hi, @SkuzyBae 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Closed** 2022-04-20 13:48 UTC
Labels: ADF_2022
